import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

interface RootLayoutProps {
  children: ReactNode;
}

const RootLayout: FC<RootLayoutProps> = ({ children }) => {
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Key Safe</title>
      </head>
      <body className={inter.className}>
        <main className="min-h-[85vh] bg-white">{children}</main>
      <body className={` ${inter.className}`}>
        <main className="min-h-[85vh] bg-white">{children}</main>
      </body>
    </html>
  );
}
